### ISSUE TITLE
Module error for Shape object 

### ISSUE THREAD

**Issue by gigiboum** [MrBlenny/py-d2#18]
### Description

Thanks a lot for this library, i’m using it for a project and it’s very useful! However, I did notice that in the _init_.py file, it’s missing the Shape object, which makes it impossible to use when trying to use a shape within a D2Shape. Locally i was able to do a “simple fix” by importing it just like the other objects, but i think it’s a better long term solution to fix it directly at the source. Also simplifies having to use it with Docker containers. Many thanks :)

**Comment by MrBlenny** [comment]
https://github.com/MrBlenny/py-d2/commit/6d11b49ce3e23942d4dfc45573b7f6d859a84493
