### ISSUE TITLE
py.typed marker missing

### ISSUE THREAD

**Issue by smheidrich** [MrBlenny/py-d2#20]
### Description

The tagline of this project says "fully typed" so I assume this is an oversight:

In order for library consumers to benefit from this library's type annotations, [there must be a `py.typed` marker](https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-type-information) in the package to signal to typecheckers that they can use them.

Otherwise, typecheckers like Mypy print errors such as:

```
error: Skipping analyzing "py_d2": module is installed, but missing library stubs or py.typed marker  [import-untyped]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

**Comment by MrBlenny** [comment]
Hopefully resolved with this
https://github.com/MrBlenny/py-d2/commit/91d62f0e60b24a6505aebba3b52905b57bd3dde5
